Design/LocalDesign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Design/catalog/urls.py
from django.urls import path
from . import views
from .views import ApplicationListView, delete_application, ApplicationAllListView

urlpatterns = [
    path('', ApplicationAllListView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('accounts/profile/', ApplicationListView.as_view(), name='profile'),
    path('accounts/profile/createapp/', views.CreateAppView.as_view(), name='createapp'),
    path(r'delete_application/<pk>', delete_application, name='delete_application'),

]

Design/catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.crypto import get_random_string


class User(AbstractUser):
    name = models.CharField(max_length=200, verbose_name='Имя', blank=False)
    surname = models.CharField(max_length=200, verbose_name='Фамилия', blank=False)
    patronymic = models.CharField(max_length=200, verbose_name='Отчество', blank=True)
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True, blank=False)
    email = models.EmailField(max_length=200, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=200, verbose_name='Пароль', blank=False)
    role = models.CharField(max_length=200, verbose_name='Роль',
                            choices=(('admin', 'Администратор'), ('user', 'Пользователь')), default='user')

    def __str__(self):
        return self.name


def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


class Application(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название', blank=False)
    username = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, verbose_name='Описание', blank=False)
    categories = models.ForeignKey('Categorise', verbose_name='Категория', on_delete=models.CASCADE)
    image = models.FileField(max_length=254, upload_to=get_name_file, verbose_name='Эскиз', null=True, blank=True)
    status = models.CharField(max_length=200, verbose_name='Статус',
                              choices=(('new', 'Новая'), ('in work', 'Принято в работу'), ('done', 'Выполнено')),
                              default='new')
    date = models.DateField(verbose_name='Дата добавления', auto_now_add=True)
    img = models.FileField(max_length=254, upload_to=get_name_file, null=True, blank=True)
    comment = models.TextField(max_length=1000, help_text="Комментарий", blank=True)

    def __str__(self):
        return self.name


class Categorise(models.Model):
    name = models.CharField(max_length=200, help_text="Напишите категорию", blank=False)

    def __str__(self):
        return self.name

Design/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>

  {% block title %}<title>TomskDisigne</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

<body>
<div class="container-fluid px-0">
    <header class="header">
            <section>
                 <h4 class="mr-md-auto p-2 text-white">TomskDisigne</h4>
                <nav>
                    <li><a  href="{% url 'index'  %}">ГЛАВНАЯ</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="" href="{%url 'profile'%}">ЛИЧНЫЙ КАБИНЕТ</a></li>
                    <li><a class="" href="{%url 'logout'%}">ВЫХОД</a></li>
                      {% else %}

                    <li><a href="{%url 'register'%}">РЕГИСТРАЦИЯ</a></li>
                    <li><a href="{%url 'login'%}">ВХОД</a>
                    {% endif %}
               </nav>
            </section>
        </header>

       <div class="bg-white ">
       <div class="window">
           <p>МЫ ПРЕДОСТАВЛЯЕМ<br> ЛУЧШИЕ РЕШЕНИЯ<br>НА РЫНКЕ</p>
                <P>Многие годы мы помогаем клиентам<br>
                    создавать интерьер их мечты. <br>ВЫ можете отправить свои эскизы, <br> а мы реализуем их и покажем<br>
                как будет выглядеть ваш будущий дом</P>
       </div>


   </div>

   <div class="bg-white">
       <div class="container bg-white m-auto-0">
       {% block content %}
       {% endblock %}
       </div>
   </div>
    {% block pagination %}
    {% if is_paginated %}
        <div class="pagination justify-content-center m-auto bg-white">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}


    <footer class="footer_part d-flex justify-content-center align-items-center ">
        <div class="copyright_part">
            <div class="container">
                <div class="row ">
                    <div class="col-lg-12">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены</P>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

</body>

</html>

Design/templates/createapp.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>TomskDisigne</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>

<body>
<div class="container-fluid px-0">
    <header class="header">
            <section>
                 <h4 class="mr-md-auto p-2 text-white">TomskDisigne</h4>
                <nav>
                    <li><a  href="{% url 'index'  %}">ГЛАВНАЯ</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="" href="{%url 'profile'%}">ЛИЧНЫЙ КАБИНЕТ</a></li>
                    <li><a class="" href="{%url 'logout'%}">ВЫХОД</a></li>
                      {% else %}

                    <li><a href="{%url 'register'%}">РЕГИСТРАЦИЯ</a></li>
                    <li><a href="{%url 'login'%}">ВХОД</a>
                    {% endif %}
               </nav>
            </section>
        </header>
<div class="bg-white ">
<p class="zgl">Создание заявки</p>
    <div class="d-flex justify-content-center for-form">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="file" name="image" id="id_image" multiple>
            <input type="submit" value="Создать">
        </form>

        <script>
            const fileInput = document.getElementById("id_image");

            fileInput.addEventListener("change", function() {
                const files = fileInput.files;
            });
        </script>
    </div>
</div>
 <footer class="footer_part d-flex justify-content-center align-items-center ">
        <div class="copyright_part">
            <div class="container">
                <div class="row ">
                    <div class="col-lg-12">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены</P>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>

Design/templates/index.html
{% extends "base_generic.html" %}


{% block content %}
 <div><P class="zgl">Выполненные планы помещений ({{count}})</P></div>


  {% if application_list %}

  <ul>
   {% for application in application_list %}
                     <div class=" box-shadow content-window">
                          <div class="d-flex ">
                                <div>
                                     <img src="{{application.image.url}}">
                                </div>
                                <div>
                                    <div class="d-flex justify-content-between">
                                         <p class="p-2"> {{application.name}} ({{application.categories}})</p>
                                        <p class="p-2"> {{application.date}} - ({{application.status}})</p>
                                    </div>
                                    <p class="p-2"> {{application.description}}</p>
                                </div>
                         </div>
                    </div>
            {% endfor %}
  </ul>
 {% else %}
    <p class="zgl">Планов помещений нет</p>
  {% endif %}

{% endblock %}

Design/templates/profile.html
{% extends "base_generic.html" %}
{% block content %}

<p class="zgl">Ваши объявления</p>

           <div class="d-flex justify-content-center">
                <p class="sl"> <a href="{% url 'profile' %}">Все</a></p>
                <p class="sl"><a href="{% url 'profile' %}?status=new"> Новые </a></p>
                <p class="sl"> <a href="{% url 'profile' %}?status=in work"> В работе</a>  </p>
                <p class="sl"> <a href="{% url 'profile' %}?status=done"> Выполненые </a></p>
            </div>

<div class="content-window ">


 <p class="sl"><a href="{% url 'createapp' %}"> + Создать новое объявление</a></p>
</div>
{% if application_list %}


  <ul>
   {% for application in application_list %}
                     <div class=" box-shadow content-window">
                          <div class="d-flex ">
                                <div>
                                     <img src="{{application.image.url}}">
                                </div>
                                <div>
                                    <div class="d-flex justify-content-between">
                                         <p class="p-2"> {{application.name}} ({{application.categories}})</p>
                                        <p class="p-2"> {{application.date}} - ({{application.status}})
                                            {% if application.status == 'new' %}
                                <a href="{% url 'delete_application' application.pk %}">Удалить заказ</a>
                            {%          endif %}</p>
                                    </div>
                                    <p class="p-2"> {{application.description}}</p>
                                </div>
                         </div>
                    </div>
            {% endfor %}
  </ul>
 {% else %}
    <p class="zgl">Объявлений нет</p>
  {% endif %}
{% endblock %}